Hosts:
  Clickhouse: "host-ch"
  K8s: "host-k8s-nodes"
  PgShared: "host-pg-shared"
  FSSO: "host-fsso"
  APIGW: "host-apigw"
  ProdClusterK8S: "host-k8s-prod"
  Zookeeper: "host-zk"
  Neo4j: "host-neo4j"
  TigerGraph: "host-tiger"
AppName: "appname"
ClusterPgShared: "cluster-pg"
DatabasePgShared: "host-pg"
NameSpace: "namespace"
